name: dozen
channels:
  - pyviz/label/dev
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - jupyter
  - pyviz=0.10
  - pip:
    - pyproj==1.9.6
    - git+https://github.com/andymcaliley/dozen
